// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

import io.github.bonigarcia.wdm.WebDriverManager;

public class HU12PresentacionEquipoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void presentacinEquipo() {
    driver.get("http://uniextremadura.github.io/gps-project-gd06/about.html");
    driver.manage().window().setSize(new Dimension(1936, 1048));
    driver.findElement(By.cssSelector(".nav-item:nth-child(1) > .nav-link")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) > .nav-link")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(3) > .nav-link")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) > .nav-link")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(4) > .nav-link")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) > .nav-link")).click();
    assertThat(driver.findElement(By.cssSelector(".col-lg-3:nth-child(1) h5")).getText(), is("Elena Barrera"));
    assertThat(driver.findElement(By.cssSelector(".col-lg-3:nth-child(2) h5")).getText(), is("Juan Boticario"));
    assertThat(driver.findElement(By.cssSelector(".col-lg-3:nth-child(3) h5")).getText(), is("Javier Mateos"));
    assertThat(driver.findElement(By.cssSelector(".col-lg-3:nth-child(4) h5")).getText(), is("Felix Exposito"));
    driver.findElement(By.cssSelector("input")).click();
    driver.findElement(By.cssSelector("input")).sendKeys("pato@pato");
    driver.findElement(By.cssSelector("form > button")).click();
  }
}
